# Generated by Django 2.1.15 on 2020-04-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_auto_20200430_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='members',
            new_name='embers',
        ),
    ]
