# Generated by Django 2.1.15 on 2020-04-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_auto_20200430_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='embers',
            new_name='members',
        ),
    ]
